name: image_to_pdf_app
description: A Flutter app to convert images to PDF.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  open_file: ^3.2.1
  pdf: ^3.6.0
  image: ^3.1.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true